### ISSUE TITLE
Travis builds fail with message - "No Rakefile found" even if the language is set as node_js in travis.yml

### ISSUE THREAD

**Issue by devsatishm** [tmobile/jazz#216]
### Description

Travis builds fail with message - 'No Rakefile found' even if the language is set as node_js in travis.yml

### Steps to Reproduce

1. Merge any branch to master which should kick off a travis build job
2. Go to https://travis-ci.org/tmobile/jazz/builds/ and latest build will fail with error - 'No Rakefile found'

**Expected behavior:**
Travis build should be marked as green if the corresponding tests pass as configured in https://github.com/tmobile/jazz/blob/master/.travis.yml

**Actual behavior:**
Unit tests are not getting triggered even if configured in travis.yml. _Travis fails to identify that the language is node_js_. This could be because Travis could not find .travis.yml during build phase and then defaults to ruby for the build language. Since rake is not configured as part of the pre-build step here, every build fails with error - 'No Rakefile found'.

**Reproduces how often:** 
100% reproducible

**Comment by suryajak** [comment]
This is fixed with our latest v1.6 release

**Comment by gitsilos** [comment]
The issue still persists

My .travis.yml file
language: ruby
sudo: required
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t k8s\client -f Dockerfile.dev .

script:
  - docker run -e CI=true -t k8s\client npm run test -- --coverages

i get the error : 

resolvconf
git.checkout
1.47s$ git clone --depth=50 --branch=master https://github.com/gitsilos/DevOps.git gitsilos/DevOps
0.01s
rvm
0.62s$ rvm use default
ruby.versions
$ ruby --version
No Gemfile found, skipping bundle install
0.14s$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-2.5.3@global/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.5.3@global/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/gems/ruby-2.5.3@global/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
Done. Your build exited with 1.


 i tried with language: generic    and language: node_js   but not worked. Something fishy
